title: IDeA Research Group
email: idea@idsia.ch
description: >-
    IDeA (Industrial Decision Analytics) is a research group working on .....
baseurl: ""
url: "https://idea.idsia.ch"

# Navigation links (order matters)
nav_links:
    - title: Home
      url: /
    - title: People
      url: /people/
    - title: Projects
      url: /projects/
    - title: Software
      url: /software/
    - title: Publications
      url: /publications/

collections:
    projects:
        output: true
        permalink: /projects/:name/
    software:
        output: true
        permalink: /software/:name/
    publications:
        output: true
        permalink: /publications/:name/

# Build settings
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-wikilinks

wikilinks:
    enabled: true

d3_graph_data:
    enabled: false

sass:
    sass_dir: _sass
    style: compressed

# How many team members to show in the home page preview (set to 0 to show all)
home_team_limit: 0

exclude:
    - Gemfile
    - Gemfile.lock
    - vendor/
    - .bundle/
